### ISSUE TITLE
Feature Suggestion: Timer on active Encounters

### ISSUE THREAD

**Issue by juan-r-apolinario** [hktrpg/foundryVTT_game_time_clock#4]
When the GM click on "Begin Combat" a timer will start and will be shown on the Combat Tracker.

**Comment by zeteticl** [comment]
> Argh! I think this new feature broke something. When I start a combat, all my players (not the GM) receive multiple error messages that keep repeating. Something like this:
> 
> > "foundry.mjs:166756 Uncaught (in promise) Error: User Alessio lacks permission to update Setting [WDppPnGgCttuC5po]
> > [No packages detected]
> > at /D:/GIOCHI/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5632
> > at async Promise.all (index 0)
> > at async ServerDatabaseBackend._updateDocuments (/D:/GIOCHI/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5384)
> > at async #try (/D:/GIOCHI/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:98:17)"
> 
> It's extremely easy to replicate, simply turn on the module, start a combat in dnd5e, and every player start getting the error.

#16  Thank you for report, just fixed the bug on 2.1.3

**Comment by davelamorte** [comment]
No, thank you!
It seems to be working now!
